[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/cli-host",
    "crates/repl-logic-guest",
    # "crates/repl-guest",
    # "crates/plugin-hello"
]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
wasmtime = { version = "33", default-features = false, features = [
    "async",
    "demangle",
    "runtime",
    "cranelift",
    "component-model",
    "incremental-cache",
    "parallel-compilation",
] }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
