[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/cli-host",
    "crates/plugin-greet",
    "crates/plugin-echo",
    "crates/plugin-ls",
    "crates/repl-logic-guest",
    "crates/plugin-weather",
    # "crates/repl-guest",
    # "crates/plugin-hello"
]

[workspace.package]
publish = false
edition = "2024"
description = "WebAssembly Component Model basic REPL with sandboxed multi-language plugin system - unified codebase runs in CLI (Rust) and web (TypeScript)"

[workspace.dependencies]
wasmtime = { version = "33", default-features = false, features = [
    "async",
    "demangle",
    "runtime",
    "cranelift",
    "component-model",
    "incremental-cache",
    "parallel-compilation",
] }
wasmtime-wasi = "33"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
wit-bindgen-rt = { version = "0.42.1", features = ["bitflags"] }
