[package]
name = "api"
version = "0.1.0"
edition = { workspace = true }
publish = false
build = "build.rs"

[dependencies]
wasmtime = { workspace = true }

[build-dependencies]
wasmtime = { workspace = true }
